### PR TITLE
[JENKINS-60507] Eventually cancel `node` blocks in anomalous status

### PR DESCRIPTION
**Pull request by jglick**
Observed during a build of https://github.com/jenkinsci/bom/pull/1832. @dduportal et al., any interest in testing this?

### CODE REVIEW

**Comment by jglick** [comment]
Probably too aggressive, trying to tune this a bit. Without knowing how to reproduce the original problem I can only guess.

**Comment by dduportal** [comment]
> Observed during a build of [jenkinsci/bom#1832](https://github.com/jenkinsci/bom/pull/1832). @dduportal et al., any interest in testing this?

Absolutely interested !

**Comment by dduportal** [comment]
@jglick just installed on ci.jenkins:

Capture d’écran 2023-03-24 à 13 30 33


Let's check how ti behaves.
Any particular point to check?

**Comment by jglick** [comment]
> Any particular point to check?

That there are no builds marked aborted improperly. If this works, it should automatically clean up certain cases of builds which were actually corrupted (letting them complete normally if `retry` is used).

**Comment by jglick** [comment]
I guess there have been no obvious problems arising from this? So I think it could be merged.

**Comment by dduportal** [comment]
> I guess there have been no obvious problems arising from this? So I think it could be merged.

Confirmed. Sorry for the delay in answer, but no issue: go go go

**Review by car-roll — APPROVED** [review]

**Pull request merged**
