### PR TITLE
add pwsh step

### PR DESCRIPTION
**Pull request by casz**
downstream of https://github.com/jenkinsci/durable-task-plugin/pull/111

Hmm, should I add docker fixture or testcontainers or hope that our Windows server 2019 have pwsh?

### CODE REVIEW

**Comment by gabloe** [comment]
@casz the Windows Server Images likely do not have open powershell (posh) installed

**Comment by gabloe** [comment]
This looks good to me.

**Comment by casz** [comment]
I think the testing done in upstream should suffice for, if anyone disagree. I can import the same test here 😓

**Comment by casz** [comment]
I updated it to use the released version, so a mighty release of this would be appreciated @dwnusbaum @car-roll 🙏

**Comment by dwnusbaum** [comment]
@casz FYI, I filed https://github.com/jenkins-infra/update-center2/pull/305 to suspend distribution of durable-task 1.31 due to some issues on various platforms from a separate change, so we don't want to merge/release this with a dependency on 1.31. We're still trying to decide what to do with that issue, we might end up releasing 1.32 that reverts/disables the problematic change and then we could update to that here, or we might try to fix the issues with https://github.com/jenkinsci/durable-task-plugin/pull/114 and then release 1.32.

**Comment by car-roll** [comment]
so 1.32 has been released and #123 has the 1.32 change as well as a changelog that covers this PR. Since ci.jenkins.io is down, I don't know if you just want to run your tests locally with 1.32 to make sure everything is okay.  Would that be good enough to merge this in @dwnusbaum ?

**Comment by casz** [comment]
Here is my basic test that demonstrate it works:

Pipeline:
```groovy
node {
    pwsh 'Write-Host "Hello from $($PSVersionTable.PSVersion) $($PSVersionTable.PSEdition)"'
    powershell 'Write-Host "Hello from $($PSVersionTable.PSVersion) $($PSVersionTable.PSEdition)"'
}
```

Run:
```
Started by user unknown or anonymous
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in C:\code\workflow-durable-task-step-plugin\work\workspace\test
[Pipeline] {
[Pipeline] pwsh
Hello from 6.2.3 Core
[Pipeline] powershell
Hello from 5.1.19008.1 Desktop
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

image

**Comment by casz** [comment]
I can add a test case @car-roll if you want :)

**Comment by casz** [comment]
@slide hmm the new Windows 2019 servers do they have powershell core or do I have to put it in docker?

**Comment by slide** [comment]
They do not have powershell core right now.

**Comment by casz** [comment]
@slide I don't see any docs for buildPlugin on how to use Windows Server 2019 for using Windows Docker 😅

**Comment by slide** [comment]
@casz good question, this is the first time this has come up so far. We may need to enhance

**Comment by car-roll** [comment]
So we are not at 1.33 for durable-task. That should resolve the issues that were introduced in 1.31. So far no other complaints, so you can go ahead and update this dependency again (sorry). I think maybe another day with no other major issues popping up, we can merge and release

**Comment by casz** [comment]
Would appreciate a release 🙏

**Comment by car-roll** [comment]
sorry for all the delays @casz 😢  Took some time to make sure durable-task 1.33 didn't introduce any more problems. I'm merging this now.

**Comment by casz** [comment]
No, thank you! Sorry for being so pushy 😓

**Pull request merged**
