### PR TITLE
[JENKINS-31842] Thread dump improvements

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/7 and https://github.com/jenkinsci/durable-task-plugin/pull/26 and https://github.com/jenkinsci/workflow-step-api-plugin/pull/4.

@reviewbybees

### CODE REVIEW

**Comment by svanoort** [comment]
🐝  looks very reasonable to me AFAICT (and prints helpful & descriptive information wherever possible)

**Comment by abayer** [comment]
:bee:

**Comment by svanoort** [comment]
🐝

**Comment by kohsuke** [comment]
:bee:

**Pull request merged**
