### PR TITLE
Deleting obsolete `ExecutorStepTest.accessPermittedOnlyFromCurrentBuild`

### PR DESCRIPTION
**Pull request by jglick**
Test introduced in #177 begins failing after https://github.com/jenkinsci/jenkins/pull/5885 and is rendered meaningless by that cleanup. Test coverage from #170 remains.

### CODE REVIEW

**Review by basil — APPROVED** [review]

**Review by dwnusbaum — APPROVED** [review]

**Review by car-roll — APPROVED** [review]

**Comment by basil** [comment]
@car-roll Would be nice to get a release of this. Without a release, this test fails in PCT / `bom-weekly` for 2.326.

**Comment by car-roll** [comment]
@basil looks like there are some issues preventing release atm

**Comment by basil** [comment]
> there are some issues

[INFRA-3165](https://issues.jenkins.io/browse/INFRA-3165) FTR

**Comment by car-roll** [comment]
@basil https://github.com/jenkinsci/workflow-durable-task-step-plugin/releases/tag/1112.vda00e6febcc1

**Comment by basil** [comment]
Thank you!

**Pull request merged**
