### PR TITLE
[FIXED JENKINS-41755] background task execution

### PR DESCRIPTION
**Pull request by kohsuke**
Please see [JENKINS-41755](https://issues.jenkins-ci.org/browse/JENKINS-41755) for the context.

### CODE REVIEW

**Comment by kohsuke** [comment]
Live from [FOSDEM Hackathon](https://www.meetup.com/jenkinsmeetup/events/236370750/) waiting for some @jglick love

**Comment by jglick** [comment]
Probably reasonable, but I am not going to touch it until #21 is merged.

**Comment by orrc** [comment]
PR works as expected, though it would be useful to be able to read the stdout & stderr from the process, despite it being in the background.

In my specific case, I would use this to check why an Android emulator process failed to launch (it writes errors to stderr (and stderr…)).

**Comment by chancez** [comment]
Is it possible this might assist in the issue at https://issues.jenkins-ci.org/browse/JENKINS-42048 ?

**Comment by jglick** [comment]
No.

**Comment by jglick** [comment]
I think this can be closed, WDYT @dwnusbaum ?

**Pull request closed without merging**
