### PR TITLE
[JENKINS-40995] Added PlaceholderTask.toString; make PlaceholderExecutable.toString safer

### PR DESCRIPTION
**Pull request by jglick**
Would make for better output with [this script](https://support.cloudbees.com/hc/en-us/articles/235690727-Why-are-jobs-on-the-queue-when-there-are-dedicated-slaves-with-free-executors) for example. Should also fix [JENKINS-40995](https://issues.jenkins-ci.org/browse/JENKINS-40995).

@reviewbybees

### CODE REVIEW

**Comment by fbelzunc** [comment]
🐝 Now, yes I get how this fix the problem.

Many thanks!

**Comment by Evildethow** [comment]
:bee:

**Comment by fbelzunc** [comment]
@jglick can you merge and release, please?

**Comment by rsandell** [comment]
:bee:

**Comment by jglick** [comment]
Will try to release shortly; waiting to see if #26 gets fixed up.

**Comment by vivek** [comment]
@jglick I have incorporated your feedback in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/26, PTAL.

**Pull request merged**
